FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run prisma:generate

EXPOSE 8080

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate dev --skip-generate && npm run dev"]
